baseurl: http://www.roadstarteam.com
title: 'roadstarteam.com'
name: '顽石[ROADSTARTEAM.COM]'
email: axl.zhao@gmail.com
slogan: '钓鱼岛是中国的，爱编程，更爱中国。'
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]
